#!/bin/bash
# QUICK START GUIDE - Copy these commands

echo "🚀 Fibre Forecast System - Quick Start Guide"
echo "=============================================="
echo ""

echo "STEP 1: Navigate to project"
echo "$ cd /home/habib/pfe"
echo ""

echo "STEP 2: Start the entire system"
echo "$ ./start_all.sh"
echo ""
echo "This will:"
echo "  - Start 9 Docker containers"
echo "  - Initialize PostgreSQL database"
echo "  - Initialize Milvus collection"
echo "  - Pull Ollama models"
echo "  - Verify all services are healthy"
echo ""

echo "STEP 3: Access the system (after ~2-3 minutes)"
echo ""
echo "🌐 Frontend:       http://localhost:3000"
echo "🔌 Backend API:    http://localhost:8000"
echo "📊 MLflow:         http://localhost:5001"
echo "📡 Phoenix:        http://localhost:6006"
echo "🗂️  Milvus Attu:   http://localhost:8001"
echo ""

echo "STEP 4: Test the API"
echo "$ curl http://localhost:8000/health"
echo "$ curl http://localhost:8000/docs  # Interactive API docs"
echo ""

echo "STEP 5: Check logs"
echo "$ docker-compose logs -f backend      # Backend logs"
echo "$ docker-compose logs -f ollama       # Ollama logs"
echo "$ docker-compose logs -f postgres     # Database logs"
echo ""

echo "STEP 6: Next, implement services"
echo "1. backend/app/services/etl_service.py"
echo "2. backend/app/services/forecasting_service.py"
echo "3. backend/app/services/rag_service.py"
echo "4. Wire up API endpoints"
echo "5. Connect frontend to APIs"
echo ""

echo "USEFUL COMMANDS"
echo "==============="
echo ""
echo "# Stop everything"
echo "$ docker-compose down"
echo ""
echo "# View database"
echo "$ docker exec -it fibre_postgres psql -U admin -d fibre_forecast_db"
echo ""
echo "# View Ollama models"
echo "$ curl http://localhost:11434/api/tags | jq"
echo ""
echo "# Restart backend"
echo "$ docker-compose restart backend"
echo ""
echo "# Rebuild backend image"
echo "$ docker-compose up -d --build backend"
echo ""
echo "# Full system rebuild"
echo "$ docker-compose down -v && docker-compose up -d"
echo ""

echo "DOCUMENTATION"
echo "============="
echo "README.md           - Project overview & setup"
echo "STATUS.md           - Detailed completion status"
echo "BUILD_SUMMARY.md    - Build summary & next steps"
echo "BUILD_MANIFEST.md   - File manifest"
echo ""

echo "✅ You're all set! Run: ./start_all.sh"
echo ""
